title: "Knrt10's Area"
email: tripathi.kautilya@gmail.com
description: An active open source contributor with almost 3 years of experience working on backend systems and developer tools using both compiled and interpreted languages while adhering to best practices. I have mostly written code in Go along with JS and Ruby professionally. Besides my industry work, I frequently contribute to various open-source projects while also building my own side projects which span over the following languages Go, JS, Typescript, Ruby, C, etc and databases like MongoDB, Elasticsearch, Redis, MySQL, etc. Contributing to open-source projects has made me well versed with software development and its best practices, including but not limited to version control, cloud-native infrastructure, databases, etc. My current interests are programming languages (especially functional programming), distributed systems, infrastructure engineering, systems programming, and databases. I like to work on distributed systems and also get to dabble in infrastructure and other aforementioned interests of mine (bonus if the projects is open sourced).

permalink: pretty
github_url: https://github.com/knrt10
sourceUrl: https://github.com/knrt10/knrt10.github.io
medium_url: https://medium.com/@knrt
linkedIn_url: https://www.linkedin.com/in/knrt10/
twitter_url: https://twitter.com/knrt19
freecodecamp_url: https://www.freecodecamp.org/knrt10
url: "https://knrt10.github.io"
resume_url: https://knrt10.github.io/resume/resume.pdf

share:
  twitter_username: knrt19
  fb_appid: 1749788565247320

exclude:
  - Gemfile*
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - node_modules
  - script
  - vendor

markdown: kramdown

highlighter: rouge

plugins:
  - jekyll-redirect-from
  - jekyll-octicons
  - jekyll-readme-index
  - jemoji

collections:
  apps:
    output: true
    permalink: /apps/:name/
  education:
    output: true
  online:
    output: true

defaults:
  - scope:
      path: ""
      type: apps
    values:
      layout: app

branch: master
